library/tulip-gui/src/CSVImportWizard.cpp
library/tulip-gui/src/CoordEditor.cpp
plugins/view/SOMView/SOMPropertiesWidget.cpp
software/tulip/src/TulipWelcomePage.cpp

error: invalid use of incomplete type ‘class QHeaderView’
error: ‘QDoubleValidator’ was not declared in this scope
error: invalid use of incomplete type ‘class QButtonGroup’

fix build with Qt 5.11

---

library/tulip-gui/include/tulip/TulipFontIconEngine.h

Fix Qt4 compilation broken at commit ef7a4ece34aa17e0bf2349ebd9955eed82dc688b

Fix Tulip build with Qt4

---

appveyor_msvc.bat
appveyor_msys2.bat

This commit fixes the MSVC builds on AppVeyor (libpng url was no more valid) and build Tulip with Python 3 only for MSYS2 in order to avoid build timeouts (limited to 1h, timeouts can still appear but less than before)

Appveyor builds: fix and improvement

---

library/tulip-python/src/PythonInterpreter.cpp

Those should have been removed in commit cbb85d6.

tulip-python/PythonInterpreter: Remove no more needed function calls

---

library/tulip-python/bindings/tulip-gui/packaging/setup.py.in

This setup should have been this way from the beginning, my bad.
tulipgui-python X.Y is only compatible with tulip-python X.Y so ensure correct version in install_requires to avoid possible version mismatch the day tulipgui-python will not be distributed on PyPI anymore.

tulipgui-python: Force version of tulip-python dependency

---

plugins/general/EdgeBundling/EdgeBundling.cpp

While attempting to bundle that graph containing nodes at the same position [air-routes-latest.tlp.gz](https://github.com/Tulip-Dev/tulip/files/2611851/air-routes-latest.tlp.gz), Tulip segfaults.
A regression was introduced in commit 728ac5dd83459eb886b8e97e00e001259d1769ba, due to the switch to static properties for better multi-threading.
The following output from the `AddressSanitizer` tool from `clang` helped me find the cause of this issue (`heap-buffer-overflow` due to a vector not resized after the add of a new edge):
```
antoine@guggenheim:~/dev/tulip_build_clang$ ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-7/bin/llvm-symbolizer ./install/bin/tulip_perspective 
Perspective running in standalone mode
================================================================= …
```

EdgeBundling: Fix segfault with input layout containing nodes with same position

---

appveyor_msys2.bat
cmake/TulipUseFile.cmake

The latest compiler toolchain available for MSYS2 users is GCC 8.2.1 and new compilation errors appear with it, quoting build log:
```
In file included from C:/msys64/mingw64/include/c++/8.2.1/bits/shared_ptr.h:52,
from C:/msys64/mingw64/include/c++/8.2.1/memory:81,
from C:/msys64/mingw64/include/cppunit/extensions/HelperMacros.h:16,
from C:/projects/tulip/tests/include/CppUnitIncludes.h:29,
from C:/projects/tulip/tests/library/tulip/ImportExportTest.h:22,
from C:/projects/tulip/tests/library/tulip/ImportExportTest.cpp:19:
C:/msys64/mingw64/include/c++/8.2.1/bits/shared_ptr_base.h:510:5: error: function 'static const std::type_info& std::_Sp_make_shared_tag::_S_ti()' definition is marked dllimport
_S_ti() noexcept _GLIBCXX_VISIBILITY(default)
^~~~~
``` 
This was due to some compiler flags …

Fix Tulip build with GCC 8.2.1 on MSYS2

---

appveyor_msvc.bat

Recent changes in upstream clcache broke the MSVC builds on AppVeyor.
Instead of compiling clcache from its development version (was the only way to
get it at the time I wrote the build script), prefer to install the stable version
from PyPI.

AppVeyor: Fix MSVC builds

---

cmake/TulipUseFile.cmake

This should fix the MacOS builds of Tulip when using clang provided by Xcode after recent CMake policy change (see https://travis-ci.org/Tulip-Dev/tulip/jobs/482469437 and https://travis-ci.org/Tulip-Dev/tulip/jobs/482469438).

Fix MacOS Xcode builds with CMake policy CMP0025 set to NEW

---

.travis.yml
README.md
cmake/TulipPython.cmake
library/tulip-gui/src/GlOffscreenRenderer.cpp
library/tulip-ogl/include/tulip/OpenGlConfigManager.h
library/tulip-ogl/src/TulipFontAwesome.cpp
library/tulip-python/src/CMakeLists.txt

I noticed Travis builds were down due to a parsing error of the yml file (tabs are not allowed for indentation in YAML). Apart from that fix, I wanted to submit some improvements regarding MacOS builds, here is a pull request compiling a couple of commits related to the subject.
Notably on Travis, the modern MacOS build based on MacPorts now uses latest upstream clang version (7.0.1) and links against qt-webkit and quazip provided by MacPorts. 
I also fixed some annoying compiler warnings that were polluting the build logs.
A couple of minor improvements and fixes are also introduced.

Reactivate TravisCI and some improvements related to MacOS builds

---

.travis.yml
bundlers/linux/tulip_appimage_centos6_build.sh
plugins/interactor/InteractorAddEdge.cpp
plugins/interactor/InteractorDeleteElement.cpp
plugins/interactor/InteractorEditEdgeBends.cpp
plugins/interactor/InteractorGetInformation.cpp
plugins/interactor/InteractorNavigation.cpp
plugins/interactor/InteractorRectangleZoom.cpp
plugins/interactor/InteractorSelection.cpp
plugins/interactor/InteractorSelectionModifier.cpp
plugins/interactor/MouseLassoNodesSelector/MouseLassoNodesSelector.cpp
plugins/view/GeographicView/GeographicViewInteractors.cpp
plugins/view/GeographicView/GeographicViewShowElementInfo.cpp
plugins/view/HistogramView/HistogramInteractors.cpp
plugins/view/ParallelCoordinatesView/ParallelCoordinatesInteractors.cpp
plugins/view/PixelOrientedView/PixelOrientedInteractors.cpp
plugins/view/SOMView/SOMViewInteractor.cpp
plugins/view/ScatterPlot2DView/ScatterPlot2DInteractors.cpp
tests/CMakeLists.txt

First PR regarding the maintenance of Tulip CI builds.
Now that's Qt4 support has been dropped and Ubuntu xenial is available as base image on TravisCI, I thought is was time to upgrade the Linux builds of Tulip to a more contemporary environment. 
Ubuntu trusty was used as the base image before but it's quite old nowadays for compiling desktop applications (its Qt5 version is 5.2.0 for instance). Migrating the builds to xenial offers updated packages with versions close to those of debian stretch (stable). Il also enables to perform legacy / modern build of Tulip (in terms of compiler, Qt and Python version) with a more concise Travis configuration. Last but not least, it gives more contemporary hints on how to build Tulip on debian based distribution.
The versions of the compilers / …

TravisCI: Migrate Linux builds from trusty to xenial 

---

library/tulip-python/bindings/tulip-core/DataSet.sip

Fix a nasty memory leak in Python bindings internals, see issue #82

DataSet.sip: Fix memory leak (#82)

---

bundlers/linux/make_appimage_bundle.sh.in

Tulip AppImage GUI was looking sad and quite outdated, see screenshot below:
That PR ensures that Tulip AppImage GUI will look more contemporary (thanks to qt gtk2 platformthemes plugin), see screenshot below:
You can download a Tulip AppImage including this fix [here](https://bintray.com/tulip-dev/tulip_binaries/download_file?file_path=Tulip-5.3.0-dev-x86_64.AppImage)

Improve Tulip AppImage GUI look and feel

---

bundlers/linux/make_appimage_bundle.sh.in

When using a GTK based desktop environment on Linux, Tulip AppImage GUI was still looking sad and outdated so properly fix that. There will still be some non critical GTK warnings remaining but at least Tulip GUI look and feel will be nice.

Fix Qt5 gtk2 platformthemes plugin integration in AppImage

---

library/tulip-python/src/PythonCppTypesConverter.cpp

I just found out a cool C++11 feature that I did not know of: [value initialization](https://en.cppreference.com/w/cpp/language/value_initialization). More details can
also be found [here](https://www.developpez.com/index/redirect/70891/Apprendre-l-initialisation-par-valeur-avec-Cplusplus-moderne-un-tutoriel-de-Andrzej-Krzemie-324-ski/).
This immediately rings a bell to me regarding some workarounds introduced a couple of years
ago to fix GCC compilation warnings. That PR removes them in favor of modern C++.

Code cleanup for PythonCppTypesConverter.cpp

---

library/tulip-gui/designer/InteractorConfigWidget.ui
library/tulip-gui/include/tulip/InteractorConfigWidget.h
library/tulip-gui/src/CMakeLists.txt
library/tulip-gui/src/InteractorConfigWidget.cpp

Make the interactor config widget great again after recently introduced changes (#76)
- set better windows title
- resinstate white background for the documentation
- remove dialog margins
- set a default size in order to get a decent display of the dialog content
- center the dialog above the Tulip window when displaying it
Before:
After:

tulip-gui/InteractorConfigWidget: Cosmetic fixes after #76 merge

---

library/tulip-python/src/PythonCodeEditor.cpp

I just found out that I broke the autocompletion list feature of the Python code editors in 7a398f0 (sigh ..., note to myself: fixing memory issues might have some unexpected side effects). Turns out that the selected text was not the one inserted in the code editor.
I also fixed a Qt warning that I did not notice before.

Python code editor fixes

---

appveyor_msys2.bat
library/tulip-core/include/tulip/Dikjstra.h

A couple of fixes for windows build:
- workaround a packaging issue for Qt5 on MSYS2 that recently broke builds (https://github.com/msys2/MINGW-packages/issues/5253)
- add missing TLP_SCOPE
By the way, there is a nice typo in Tulip source code: it's not Di**kj**stra but [Di**jk**stra](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm), see grep output below:
```
$ grep -ri dikjstra *
library/tulip-core/include/tulip/Dikjstra.h:#ifndef DIKJSTRA_TOOL_H
library/tulip-core/include/tulip/Dikjstra.h:#define DIKJSTRA_TOOL_H
library/tulip-core/include/tulip/Dikjstra.h:class TLP_SCOPE Dikjstra {
library/tulip-core/include/tulip/Dikjstra.h:  Dikjstra(const Graph *const graph, node src, const EdgeStaticProperty<double> &weights,
library/tulip-core/include/tulip/Dikjstra.h:  struct DikjstraElement …
```

Windows build fixes

---

library/tulip-gui/src/TulipItemDelegate.cpp
library/tulip-gui/src/TulipItemEditorCreators.cpp
plugins/glyph/fonticon.cpp

This PR improves the rendering of edge extremities as icons (see #104).
The purpose is to better encode the edge direction through icon rotations.
As interesting icons to use as edge extremities are usually symmetric along
their Y axis, the idea to encode edge direction is to:
- anchor the bottom of the icon to the source node
- anchor the top of the icon to the target node
I have also noted that the icon must also be mirrored along its Y-axis to get
a correct rendering.
For instance, when one wants to use the following fontawesome icons as edge extremities: 
On the following graph:
Before that PR, the rendering of edge extremities as icons was the following:
After that PR, the rendering of edge extremities as icons is now the following:
Nevertheless, we should give the user more …

Improve edge extremities icon rendering

---

library/tulip-core/include/tulip/Dijkstra.h
library/tulip-core/include/tulip/GraphMeasure.h
library/tulip-core/src/CMakeLists.txt
library/tulip-core/src/Dijkstra.cpp
library/tulip-core/src/GraphMeasure.cpp
library/tulip-core/src/GraphTools.cpp
plugins/general/EdgeBundling/Dijkstra.cpp
plugins/general/EdgeBundling/Dijkstra.h

Let's show [Dijkstra](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) some respect by not mispelling his name.
Fortunately, the Dijkstra class in tulip-core is part of the private API so this can be merged for Tulip 5.3.1

Fix typo in Tulip source code: dikjstra -> dijkstra

---

library/tulip-core/include/tulip/SimpleTest.h
library/tulip-core/src/SimpleTest.cpp
library/tulip-python/bindings/tulip-core/SimpleTest.sip
plugins/selection/MultipleEdgeSelection.cpp
plugins/selection/MultipleEdgeSelection.h
plugins/test/Simple.cpp

The goal of this PR is to add more flexibility for handling directed graphs. I focus here on testing whether a graph is "simple" or not and the selection/removal of multiples edges.
In the current version, Simple tests and multiple edges selection is only defined for undirected graphs. While it is true than "being simple" is theoretically only defined for undirected graphs, testing if multiple arcs a->b exist would be a nice feature to have in Tulip. Right now, we need to write a python script in order to do so while the functionality is pretty basic.  
- Class `SimpleTest`: add a `directed` parameters (with default value `false`) to member function `isSimple`, `makeSimple` and `SimpleTest`. Since this class is a singleton that save previous test in a map, we now have two singletons (for …

Add directed parameters to SimpleTest based methods and plugins.

---

library/tulip-core/src/SimpleTest.cpp

Issue #117 is due to a bug in `tlp::SimpleTest::makeSimple` implementation.
The vector of removed edges filled by the method could contain duplicated
edges in it which could lead to processing errors in client code.

SimpleTest: Ensure no duplicated edges in removed vector

---

doc/python/apichanges.rst
library/tulip-python/bindings/tulip-core/Module.sip
library/tulip-python/bindings/tulip-core/PropertyProxy.sip
tests/python/test_graph_properties.py

I found a way to fix #120 while ensuring no regression on the `tulip-python` features implemented so far (thanks to the great hacking features provided by [SIP](https://www.riverbankcomputing.com/software/sip/intro) and the strong unit tests I wrote by the past). I must admit that this behavior was quite confusing and annoying.
You can now safely write in your Tulip-Python code:
```python
viewLayout = graph.getLayoutProperty('viewLayout')
viewLayout[n] = (0, 0)
viewLayout[n] = (10.5, 0, 1.5)
viewSize = graph.getSizeProperty('viewSize')
viewSize[n] = (2, 2)
viewSize[n] = (1.5, 1, 1)
graph['viewLayout'][n] = (0, 0)
graph['viewLayout'][n] = (10.5, 0, 1.5)
graph['viewSize'][n] = (2, 2)
graph['viewSize'][n] = (1.5, 1, 1)
```

tulip-python: Add int tuples support for layout and size properties

---

plugins/colors/DoubleStringsListRelationDialog.cpp
plugins/colors/DoubleStringsListRelationDialog.h
plugins/colors/DoubleStringsListRelationDialog.ui

See Issue #121 for discussion.
Add a `QCheckBox` in the `DoubleStringsListRelationDialog` dialog:
When checked, an interpolation is made to map each value to a color based on the current color scale. 
When unchecked, replace the color mapping with the last set of non-interpolated colors.
New window with box unchecked:
New window with box checked:

Add Color Interpolation for Enumerated Color Mapping

---

plugins/general/EdgeBundling/EdgeBundling.cpp

I stumbled across a segfault when trying to bundle a particular input graph.
When the graph to bundle already has a subgraph named "Voronoi", the wrong routing grid is picked which can lead to a segfault.

EdgeBundling: Fix possible segfault for a corner case input graph

---

library/tulip-core/include/tulip/Circle.h
library/tulip-core/include/tulip/Vector.h
library/tulip-core/include/tulip/vectorgraphproperty.h
library/tulip-gui/include/tulip/PluginManager.h
library/tulip-gui/include/tulip/TulipMetaTypes.h
library/tulip-ogl/include/tulip/Camera.h
plugins/import/WebImport.cpp

When you are working on a C++ project, there is a simple rule to follow: if GCC starts emitting new warnings when its version evolves (see https://ci.appveyor.com/project/tulip-dev/tulip/build/job/wa5ql0gfd9oqtpgx?fullLog=true) and you did not touch any build configuration, you have to fix them and not ignore them.
Indeed, it gives you hints on how improve the performance of the produced binaries.
Tulip is not the only project experiencing these new warnings, see for instance https://github.com/tsduck/tsduck/issues/205 or https://github.com/freedesktop/libreoffice-cppunit/commit/78e64f0edb4f3271a6ddbcdf9cba05138597bfca

Fix -Wdeprecated-copy GCC 9 warnings

---

library/tulip-python/bindings/tulip-gui/__init__.py

I made a mistake regarding indentation level when reformatting the code which makes
the `tulipgui` module quite unusable when using the classical Python interpreter, so fixing
the issue before the release.

tulip-python/tulipgui: Fix regression introduced in 212228b

---

library/tulip-gui/src/Perspective.cpp
library/tulip-gui/src/View.cpp

Just found this bug by looking at issue #133: when a view is created outside Tulip from the classical Python interpreter and the display of a context menu is requested => SEGFAULT

tulip-python/tulipgui: Fix segfaults when requesting context menu

---

library/tulip-python/bindings/tulip-gui/TulipViewsUtils.cpp

This fixes issue #133, the OpenGL viewport was not correctly updated after resizing a standalone view. As a consequence, the view to world projection was returning bad results.

tulip-python/tulipgui: Fix viewport update after resizing a view

---

library/tulip-ogl/src/GlVertexArrayManager.cpp

I experienced a segfault when editing a graph with metanodes and selecting elements.
```gdb
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
TLP_PLATEFORM linux
TLP_ARCH x86_64
TLP_COMPILER gcc
TLP_VERSION 5.3.1
TLP_STACK_BEGIN
#00 0x00007fae672aee97 in gsignal (+0xc7) at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 from /lib/x86_64-linux-gnu/libc.so.6                                                                                                                  
#01 0x00007fae672b0801 in abort (+0x141) at /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79 from /lib/x86_64-linux-gnu/libc.so.6          
#02 0x00007fae67905957 in ?? (+0x8c957) from /usr/lib/x86_64-linux-gnu/libstdc++.so.6 …
```

tulip-ogl/GlVertexArrayManager: Fix segfault with selected graph elements

---

plugins/perspective/GraphPerspective/src/GraphPerspective.cpp

This fixes the observed crash when requesting the auto-completion list for Tulip algorithms in Python code editors.
I managed to identify where the issue was using `valgrind`, see output below:
```
==515== Invalid read of size 8
==515==    at 0x60FF46B: QListWidget::count() const (in /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.11.3)
==515==    by 0x1E19489F: addItem (qlistwidget.h:217)
==515==    by 0x1E19489F: tlp::PythonCodeEditor::updateAutoCompletionList(bool) (PythonCodeEditor.cpp:1282)
==515==    by 0x1E1A8048: tlp::PythonShellWidget::updateAutoCompletionList(bool) (PythonShellWidget.cpp:299)
==515==    by 0x1E1924BF: tlp::PythonCodeEditor::showAutoCompletionList(bool) (PythonCodeEditor.cpp:1217)
==515==    by 0x1E198737: tlp::PythonCodeEditor::keyPressEvent(QKeyEvent*) …
```

GraphPerspective: Delete static resources only when exiting Tulip (#145)

---

plugins/view/ScatterPlot2DView/ScatterPlot2DView.cpp

This PR prevents possible crash when loading a ScatterPlotView from old configuration saved in a TLPX file (see #147).

ScatterPlotView: Fix possible crash with bogus input data (#147)

---

CMakeLists.txt
appveyor_msys2.bat

Due to recent MSYS2 updates, the current AppVeyor job for Tulip complete build on MSYS2 is currently failing as it hangs when trying to generate the Tulip NSIS installer. Using a different way to escape that command is now required to fix that issue.
I also noticed QtWebKit is no more detected at the moment as its package has not been rebuilt against the last Qt5 version available on MSYS2: 5.12.4, I have added a workaround to fix its detection.

Fix Appveyor MSYS2 job for Tulip complete build

---

software/CMakeLists.txt

[binutils](https://www.gnu.org/software/binutils/) has been [upgraded to version 2.32](https://github.com/msys2/MINGW-packages/commit/1ccbe5331faf0f04123c1f590e026f5e202454df) on MSYS2, unfortunately this [breaks Tulip build](https://ci.appveyor.com/project/tulip-dev/tulip/builds/26531803/job/9wt3r1mr2i9pn2o7) as the [`windres`](https://sourceware.org/binutils/docs/binutils/windres.html) compiler now ends up with errors.
This comes from the fact that the C++ compiler options are passed by CMake to `windres` but this is not needed at all for Tulip. So ensure those options are discarded by overriding the [CMAKE_RC_COMPILE_OBJECT](https://github.com/Kitware/CMake/blob/114c52fa5b890092e1409c232c97733a8c04d5bf/Modules/CMakeRCInformation.cmake#L45-L46) variable.
A similar issue has been …

Fix Tulip compilation with binutils 2.32 on MSYS2
